services:
  - type: web
    name: your-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      export FLASK_APP=slots.py
      flask run --host=0.0.0.0 --port=$PORT
    envVars:
      - key: FLASK_ENV
        value: production
